# Site
repository: dev-loggi/dev-loggi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 조성록
title: Android Developer
email: jsl663663@gmail.com
website: github.com/dev-loggi

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: dev-loggi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 블로그
  icon: fas fa-blog
  url: https://jsl663.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 디자인에 욕심이 많은 안드로이드 개발자 조성록입니다.<br/>
  Android Modern UI/UX 관심과 이해도가 높습니다.<br/>
  Kotlin, OOP, Design Pattern, Functional Programming, Clean Code, Clean Architecture<br/>
  소프트웨어 아키텍처와 프로그래밍 패러다임에 관심이 많습니다.

content:
  # Experience
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 판게아솔루션
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 안드로이드 앱 개발 (인턴)
        caption: 2017.03 - 2017.08
        quote: >
          소셜 목표 일기 "GoalGetter" SNS 안드로이드 앱 서비스 개발
        description: |
          - 6개월 인턴십 기간 동안 개발하여 스토어에 출시한 첫 실무 앱
          - 회원, 게시물, 메신저, 광고 등 총 23개 화면 및 기능 개발
          - SQLite를 활용하여 메신저 성능 개선

  # Education
  - title: Education
    layout: list
    content:
      - layout: left
        title: KT AIVLE School 3기
        caption: 2023.02 - 2023.07
        sub_title: KT
        description: |
          - AI 모델링을 위한 데이터 분석, 머신러닝, 딥러닝(CV, NLP) 이론 및 실습
          - AI 서비스 개발을 위한 MLOps, FE, BE, AWS 클라우드 이론 및 실습
          - 교과목별 학습 과정에 대한 실습을 위한 미니 프로젝트 수행
          - 빅프로젝트 - AI 기반 대형생활폐기물 간편 배출 앱 “퍼니버니” (우수상🏆)
      - layout: left
        title: SW 알고리즘 특강
        caption: 2022.07 - 2023.08
        sub_title: 삼성전자
        description: |
          - SW 자료구조 및 알고리즘 이론 강의 및 실전 문제 풀이
          - 주어진 문제에 적합한 자료구조를 직접 설계 및 구현
          - SW Expert Academy - Professional(Level B) 취득

  # Projects
  - title: Projects
    layout: list
    content:
      - layout: left
        title: 퍼니버니
        caption: 2023.06 - 2023.07
        sub_title: Tech Lead, Android
        additional_links:
          - title: KT-AIVLE-3rd-AI-Team10/funibuni-fe-android
            icon: fab fa-github
            url: https://github.com/KT-AIVLE-3rd-AI-Team10/funibuni-fe-android
        quote: >
          AI 기반 대형생활폐기물 간편 배출 앱
        description: |
          - KT AIVLE School 6인 팀 프로젝트 (우수상🏆)
          - AI 모델 설계, 시스템 아키텍처, ERD, API 설계, 테스트, 서버 구축 등 개발 기술 코치 담당
          - Clean Architecture, MVVM, Repository 패턴 활용하여 관심사 분리
          - 공통 Design System 모듈화

  # Skills
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Android (중)
        description: |
          - Kotlin, Java
          - Multi Module, Clean Architecture, Repository Pattern, MVVM, MVP
          - Jetpack AAC (ViewModel, LiveData, DataBinding), Navigation
          - Dagger Hilt
          - Retrofit2, Okhttp3, Coroutines Flow
          - Room, Datastore
      - layout: left
        title: Backend (하)
        description: |
          - AWS EC2, S3, RDS
          - NGINX, uWSGI
          - Django, Python
          - REST API, JWT
      - layout: left
        title: Frontend (기초)
        description: |
          - HTML, CSS, Javascript
          - Chrome Extensions

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag